url: https://pauleysasphalt.com
# baseurl: /agency-jekyll-theme/

# Site settings
title: Pauley's Asphalt
email: your-email@domain.com
description: "Pauley's Asphalt: Central Kentucky Asphalt Services Call 502-680-0423 for estimates."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/PauleysAsphalt/

# Postal address (add as many lines as necessary)
address:
  - line: Lawrenceburg, KY 40342

# Build settings
markdown: kramdown
permalink: pretty